### ISSUE TITLE
TF2 API availability

### ISSUE THREAD

**Issue by vanem** [rapyuta-robotics/rclUE#104]
Looking through the documentation there is no mention of TF in rclUE. Is there a way to use lookupTransform() API?

**Comment by yuokamoto** [comment]
Currently don't have plan to support lookupTransform() since transformation among actors can be easily get from UE API.
Are there any case that you need lookupTransform?

**Comment by vanem** [comment]
I would like to use UE as a source for high quality camera video stream for example, but leave physics simulation outside of it.
Having access to the TF API (broadcast and listen) from rclUE would allow seamless integration. I could also use robot_state_publisher to publish and use TF from URDF.  I will try to look over your turtlebot example simulation soon, but doesn't the navigation uses tf?
Tf is such an integral part of ROS, would it be difficult to port it to rclUE?

**Comment by yuokamoto** [comment]
You can access TF by publish/subscribe /tf topic directly.
Please check 
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/blob/devel/Source/RapyutaSimulationPlugins/Private/Tools/RRROS2TFPublisher.cpp

**Comment by yuokamoto** [comment]
Please repoen if you have more request/question
