### ISSUE TITLE
Make RosFluidPressure: Missing Connector for pressure and variance

### ISSUE THREAD

**Issue by LukasD97** [rapyuta-robotics/rclUE#138]
![Screenshot from 2024-04-04 10-48-04](https://github.com/rapyuta-robotics/rclUE/assets/116585328/29910d82-3828-4623-830f-588092cfafe8)
The Connector to set the Pressure is missing in the Blueprint Node.
Is there an option i missed out or is this an bug?
I'm using UE 5.3.2 and tired the devel and UE 5.3 branch of this repo. ROS2 version is Humble.
For the IMU Message the node has all its connectors.
Thanks!

**Comment by LukasD97** [comment]
Solved by modifiing UPROPERTY(EditAnywhere) -> UPROPERTY(EditAnywhere, BlueprintReadWrite)
in rclUE/Source/rclUE/Public/Msgs/ROS2FluidPressure.h

**Comment by yuokamoto** [comment]
Hello, it is same issue as this
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/issues/271#issuecomment-1997416677

 BP does not support double

**Comment by LukasD97** [comment]
Hi, thanks. 
For me double works after the change, but it's a float.
![Screenshot from 2024-04-04 15-44-28](https://github.com/rapyuta-robotics/rclUE/assets/116585328/6b9c3539-45ea-424e-87ba-0cf2867cf416)

**Comment by yuokamoto** [comment]
Oh, interesting. Thanks for letting us know.
I will check and make all doubles accesible from BP if possible

**Comment by LukasD97** [comment]
No Problem :)
It would be nice

**Comment by yuokamoto** [comment]
I created PR
https://github.com/rapyuta-robotics/rclUE/pull/139
