### ISSUE TITLE
UE4 Engine Version

### ISSUE THREAD

**Issue by saratrajput** [rapyuta-robotics/rclUE#21]
May I know the UE4 engine version for the compatibility of this plugin?

**Comment by james-yoo** [comment]
Hi @saratrajput,
As far as I know, this plugin only works under following configuration:
- Ubuntu 20.04
- Unreal Engine 4.27
- ROS2 Foxy

It was not compiled under Unreal Engine 4.26 version.

**Comment by yuokamoto** [comment]
Thanks for your interests.
Yes. Ubuntu 20.04, UnrealEngine 4.27, ROS2 Foxy. I'll add those info to README.

**Comment by yuokamoto** [comment]
https://github.com/rapyuta-robotics/rclUE/pull/22
