### ISSUE TITLE
Only works when ROS_DOMAIN_ID is zero

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/rclUE#23]
Hi Rapyuta team,

Currently, this plugin only works under default ROS_DOMAIN_ID(e.g. zero). 
When I changed to value other than zero, topics or nodes are not output as follow.

```
$ export ROS_DOMAIN_ID=10
$ ros2 topic list
/parameter_events
/rosout
```

**Comment by metabotics** [comment]
Self resolved. I have found following line in 'run_editor.sh'.

unset ROS_DOMAIN_ID

Comment that line resolved the issue.

**Comment by james-yoo** [comment]
Self resolved. I have found following line in 'run_editor.sh'.

unset ROS_DOMAIN_ID

Comment that line resolved the issue.
