### ISSUE TITLE
Error - How to add this plugin to an Unreal Engine 4 project (Ubuntu 20):

### ISSUE THREAD

**Issue by thejeshk** [rapyuta-robotics/rclUE#29]
Hi 
Could you please add some additional points here: "How to add this plugin to an Unreal Engine 4 project (Ubuntu 20):" ? 
Questions: 
- Where to add the shell script? Do we need to create a file ? or ? 

I am getting an error! "Unable to compile because the built modules are out of date"  
Can you please help me solve issue ?

**Comment by yuokamoto** [comment]
Thanks you for your interst.
Please check https://github.com/rapyuta-robotics/turtlebot3-UE repository which uses rclUE as a plugin.
