### ISSUE TITLE
UE5 support?

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/rclUE#43]
Hi Rapyuta-robotics team,

EpicGames officially released UE5 recently. Do you have plan to support UE5 version?

**Comment by yuokamoto** [comment]
We are evaluating UE5 but support may not happen soon since UE5 is a bit heavier. it require large space to build and it is a bit more GPU heavier.

**Comment by james-yoo** [comment]
@yuokamoto 
Got it. Thanks for quick response!
