### ISSUE TITLE
Using ROS2 Humble

### ISSUE THREAD

**Issue by Remi-Niel** [rapyuta-robotics/rclUE#61]
Hi Rapyuta-robotics team,

I was wondering whether ROS2 Humble is or will be supported since it is next LTS version of ROS2 and Foxy is approaching EOL date.

**Comment by yuokamoto** [comment]
Hello, Thanks to have interested in our project.
Yes, we are planning to support ROS2 Humble. Since we were busy for ROSCon, we will work on Humble support later.

**Comment by tomkimsour** [comment]
I'd be very interested in a humble version as well. If that ever comes

**Comment by tomkimsour** [comment]
If anyone is interested. I am trying to make it work and compile with ros humble on unreal 5.1 as well as RapyutaSimulationPlugins

**Comment by yuokamoto** [comment]
We are working on that too. Currently following repos have UE5_devel branch we are testing with UE5.1
- turtlebot3-UE 
- RapyutaSimulationPluginsh

rclUE should work with devel branch but we are not tested many time/many cases yet.
cc @Tadinu

**Comment by yuokamoto** [comment]
I created rclUE branch UE5_devel_humble. Havne't tested fully but build pass and ROS2Examples levels works.

**Comment by tomkimsour** [comment]
> I created rclUE branch UE5_devel_humble. Havne't tested fully but build pass and ROS2Examples levels works.

I will look it up. Thanks a lot

**Comment by yuokamoto** [comment]
This cussion is keep happening in
https://github.com/rapyuta-robotics/rclUE/issues/78
