### ISSUE TITLE
How are generated libue_msgs_rosidl_*.so

### ISSUE THREAD

**Issue by tomkimsour** [rapyuta-robotics/rclUE#70]
Hi, I am trying to port this plugin to unreal 5.1 using ros humble and while updating .so files I found these libue_msgs_rosidl lib and was wondering where they were coming from. How can I generate them ?

**Comment by yuokamoto** [comment]
We uses this repo to build libs
https://github.com/rapyuta-robotics/UE_tools

but because of  changes in UE5.1 clang version, there is a issue to build it.
hope we can solve it by end of this weekl.

cc @tetorea
