### ISSUE TITLE
I got error when I add RapyutaSimulationPlugins and rclUE as plugin.

### ISSUE THREAD

**Issue by YuminosukeSato** [rapyuta-robotics/rclUE#96]
I got error when I add RapyutaSimulationPlugins and rclUE as plugin.
I add RapyutaSimulationPlugins and rclUE in UnrealEngine/Engine/Plugin Folder and I do ./Setup.sh && ./GenerateProjectFiles.sh && make.
Then, I got error.
[error.txt](https://github.com/rapyuta-robotics/rclUE/files/11714059/error.txt)
How do I solve this error?

**Comment by Tadinu** [comment]
You should setup the UE project folder similar to [turtlebot3-UE](https://github.com/rapyuta-robotics/turtlebot3-UE/tree/devel/Plugins)
